server {
    listen 80;
    server_name shipwatch.zainfor.cn;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name shipwatch.zainfor.cn;

    ssl_certificate /etc/letsencrypt/live/shipwatch.zainfor.cn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shipwatch.zainfor.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://172.18.0.1:7890;
        include proxy.conf;
    }
}
